# Generated by Django 3.2.5 on 2021-07-22 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type_bill', models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SAIDA')], max_length=1)),
                ('value', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_recourrent', models.BooleanField(default=False)),
            ],
        ),
    ]
