# Generated by Django 3.2.5 on 2021-07-22 12:50

from django.db import migrations
import minhascontas.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', minhascontas.authentication.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
